# config.yaml
input_file: "data/Suzhou_sight_data.json"
output_file: "data/Suzhou_sight_data_cleaned_output.json"
db_config:
  host: "47.113.192.168"
  user: "ecotour"
  password: "ecotour!123"
  database: "ecotour"
webdriver_path: "/usr/local/bin/chromedriver"


