server.port: 8080

# 微信小程序api配置
wx:
  app-id: 'wx916723e144727550'
  app-secret: 'ac83c25918f091165f8665177b3e45e4'

# springdoc-openapi项目配置
springdoc:
  # 将对象参数转为 k-v 模式
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  info:
    # 标题
    title: '生态旅游AI小程序接口文档'
    # 描述
    description: '生态旅游AI小程序后端, 具体包括后端web模块, 爬虫模块'
    # 版本
    version: 'V1.0.0'
    # 作者信息
    contact:
      name: InwardFlow
      email: admin@2wxk.com
      url: https://github.com/inwardflow
  # 这里定义了两个分组，可定义多个，也可以不定义
  group-configs:
    - group: 小程序模块
      packages-to-scan: com.zillionwon.web

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# DataSource Config
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
    # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能(对数据库有性能损耗 使用批量操作应考虑性能问题)
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.192.168:3306/ecotour?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&max_allowed_packet=1073741824&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: ecotour
    password: ecotour!123
  data:
    redis:
      host: 47.101.220.93
      port: 16379
      password: ecotour!123
      timeout: 1s
      database: 0


# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto

# security配置
security:
  # 排除路径
  excludes:
    # 静态资源
    - /*.html
    - /**/*.html
    - /**/*.css
    - /**/*.js
    # 公共路径
    - /favicon.ico
    - /error
    # swagger 文档配置
    - /*/api-docs
    - /*/api-docs/**
    # actuator 监控配置
    - /actuator
    - /actuator/**
